### ISSUE TITLE
undefined is not a function (evaluating 'Uint8Array.from(this._hash)')

### ISSUE THREAD

**Issue by yangjun** [netifi-proteus/proteus-js#29]
react native 0.58 + proteus-js 1.6.0
```
04-23 15:01:42.781 17632 17720 E AndroidRuntime: com.facebook.react.common.JavascriptException: undefined is not a function (evaluating 'Uint8Array.from(this._hash)'), stack:
04-23 15:01:42.781 17632 17720 E AndroidRuntime: bytes@695:666
04-23 15:01:42.781 17632 17720 E AndroidRuntime: encodeDestinationSetupFrame@702:862
04-23 15:01:42.781 17632 17720 E AndroidRuntime: encodeFrame@699:276
04-23 15:01:42.781 17632 17720 E AndroidRuntime: create@629:4198
04-23 15:01:42.781 17632 17720 E AndroidRuntime: <unknown>@627:123
04-23 15:01:42.781 17632 17720 E AndroidRuntime: _@2:1514
04-23 15:01:42.781 17632 17720 E AndroidRuntime: d@2:967
04-23 15:01:42.781 17632 17720 E AndroidRuntime: o@2:435
04-23 15:01:42.781 17632 17720 E AndroidRuntime: <unknown>@623:550
04-23 15:01:42.781 17632 17720 E AndroidRuntime: _@2:1514
04-23 15:01:42.781 17632 17720 E AndroidRuntime: d@2:967
04-23 15:01:42.781 17632 17720 E AndroidRuntime: o@2:435
04-23 15:01:42.781 17632 17720 E AndroidRuntime: <unknown>@359:293
04-23 15:01:42.781 17632 17720 E AndroidRuntime: _@2:1514
04-23 15:01:42.781 17632 17720 E AndroidRuntime: d@2:967
04-23 15:01:42.781 17632 17720 E AndroidRuntime: o@2:435
04-23 15:01:42.781 17632 17720 E AndroidRuntime: <unknown>@11:78
04-23 15:01:42.781 17632 17720 E AndroidRuntime: _@2:1514
04-23 15:01:42.781 17632 17720 E AndroidRuntime: d@2:897
04-23 15:01:42.781 17632 17720 E AndroidRuntime: o@2:435
04-23 15:01:42.781 17632 17720 E AndroidRuntime: global code@1270:4
04-23 15:01:42.781 17632 17720 E AndroidRuntime:
04-23 15:01:42.781 17632 17720 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:54)
04-23 15:01:42.781 17632 17720 E AndroidRuntime:        at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:38)
04-23 15:01:42.781 17632 17720 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-23 15:01:42.781 17632 17720 E AndroidRuntime:        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
04-23 15:01:42.781 17632 17720 E AndroidRuntime:        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
```

**Comment by hypothete** [comment]
Hi yangjun, I responded to your issue on the Netifi Community board: https://community.netifi.com/t/react-native-proteus-js-websocket-will-not-automatically-reconnect-to-proteus-broker/132/7
